# # docker run -p 80:5000 banaki9415/solar-irr
---
- name: clone webapp
  git:
    repo: https://github.com/HongPhuMagic/LoL-na-op-gg-webscrape.git
    clone: yes
    dest: /home/ec2-user/automate-prometheus-ansible/roles/webapp_contain/files
    force: yes


- name: Install python-pip
  yum:
    name: python-pip
    state: installed


- name: Install Docker-py for Ansible
  pip:
    name: docker-py


- name: pull anaconda image
  docker_image:
    name: continuumio/anaconda3


- name: build lol-webscrap image
  docker_image:
   path: /home/ec2-user/automate-prometheus-ansible/roles/webapp_contain/files/Dockerfile
   name: lol-web-image


- name: create container
  docker_container:
    name: web
    image: lol-web-image
    state: started
    ports:
    - "80:5000"
    tty: true                        #hypen t and d
    detach: true
